/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* TRANSACTIONS */
export const TRANSACTIONS_GET_LIST = 'TRANSACTIONS_GET_LIST';
export const TRANSACTIONS_GET_LIST_SUCCESS = 'TRANSACTIONS_GET_LIST_SUCCESS';
export const TRANSACTIONS_GET_LIST_ERROR = 'TRANSACTIONS_GET_LIST_ERROR';
